cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/fonts'

brew 'wget'
brew 'zsh'
brew 'dockutil'
brew 'the_silver_searcher'
brew 'coreutils'
brew 'imagemagick'
brew 'jq'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'iterm2'
cask 'font-hack'
